version: '3'

services:
  geocode-task:
    image: geocode-task:1.3
    container_name: "geocode-task"
    depends_on:
      - mongo
    ports:
      - "6000:8080"
    environment:
      - MONGO_HOST=mongo

  mongo:
    image: mongo:latest
    container_name: "mongo-geocode"
    ports:
      - "27015:27017"
    volumes:
      - ./docker/volumes/mongo:/var/lib/mongo/data

