logging:
  level:
    me:
      dyatkokg:
        geocodetask:
          client:
            YandexGeocoderClient: DEBUG

api:
  external:
    yandex-geocoder:
      name: yandex-geocoder-client
      url: https://geocode-maps.yandex.ru/1.x/

management:
  endpoints:
    web:
      exposure:
        include: "*"

